=== pypi-data/pypi-mirror-98/packages/LbNightlyTools/LbNightlyTools-3.0.28-py3-none-any.whl/LbPeriodicTools/TestSchedule.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="periodictests">
		<xsd:complexType>
			<xsd:sequence maxOccurs="unbounded" minOccurs="0">
                <xsd:element name="periodictest" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="schedule"  maxOccurs="1">
								<xsd:complexType>
								    <xsd:simpleContent>
								      <xsd:extension base="xsd:string">
								       <xsd:attribute name="type" type="xsd:string"/>
								   	   <xsd:attribute name="time" type="xsd:string"/>
								    </xsd:extension>
								  </xsd:simpleContent>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="slot" type="xsd:string" maxOccurs="1" />
							<xsd:element name="project" type="xsd:string" maxOccurs="1" />
							<xsd:element name="platform" type="xsd:string" maxOccurs="1" />
							<xsd:element name="test" minOccurs="1" maxOccurs="1">
								<xsd:complexType>
									<xsd:attribute name="group" type="xsd:string" use="required"/>
									<xsd:attribute name="runner" type="xsd:string" use="optional"/>
									<xsd:attribute name="env" type="xsd:string" use="optional"/>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="os_label" type="xsd:string" minOccurs="0" maxOccurs="1" />
							<xsd:element name="count" type="xsd:string" minOccurs="0" maxOccurs="1" />
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
            </xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== pypi-data/pypi-mirror-98/packages/LbNightlyTools/LbNightlyTools-3.0.28.tar.gz/LbNightlyTools-3.0.28/testdata/periodic_tests/scheduleIncorrect.xml
<?xml version="1.0" encoding="UTF-8"?>
<periodictests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TestSchedule.xsd">
  <periodictest>
    <schedule>Lun,Wed,Fri</schedule>
    <slot>test-slot</slot>
    <project>project</project>
    <platform>plaftorm</platform>
    <test group="testname"/>
    <os_label>os_label</os_label>
  </periodictest>
</periodictests>

=== pypi-data/pypi-mirror-98/packages/LbNightlyTools/LbNightlyTools-3.0.28.tar.gz/LbNightlyTools-3.0.28/testdata/periodic_tests/lhcbpr_schedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<periodictests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TestSchedule.xsd">
  <periodictest>
    <schedule type="week" time="19:00">Mon,Tue,Wed,Thu,Fri</schedule>
    <slot>lhcb-head</slot>
    <project>Brunel</project>
    <platform>x86_64-slc6-.*-opt</platform>
    <test runner="lhcbpr" group="TEST-COLLISION12-1000" env="UsePRConfig"/>
    <os_label>perf</os_label>
  </periodictest>
  <periodictest>
    <schedule type="week" time="19:00">Mon,Tue,Wed,Thu,Fri</schedule>
    <slot>lhcb-compatibility</slot>
    <project>Brunel</project>
    <platform>x86_64-slc5-gcc43-opt</platform>
    <test runner="lhcbpr" group="TEST-COLLISION12-1000" env="UsePRConfig"/>
    <os_label>perf</os_label>
  </periodictest>
</periodictests>

=== pypi-data/pypi-mirror-98/packages/LbNightlyTools/LbNightlyTools-3.0.28.tar.gz/LbNightlyTools-3.0.28/testdata/periodic_tests/schedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<periodictests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TestSchedule.xsd">
  <periodictest>
    <schedule>Mon,Wed,Fri</schedule>
    <slot>test-slot</slot>
    <project>project</project>
    <platform>plaftorm</platform>
    <test type="qmtest" group="testname"/>
    <os_label>os_label</os_label>
  </periodictest>
  <periodictest>
    <schedule type="month" time="12:00">1,15,20</schedule>
    <slot>lhcb-head</slot>
    <project>Brunel</project>
    <platform>x86_64-slc6-gcc46-.*</platform>
    <test runner="lhcbpr" group="PRTEST-COLLISION12-1000" env="UsePRConfig"/>
    <os_label>slc6</os_label>
    <count>30</count>
  </periodictest>
</periodictests>
